language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: VyjMu2aGE8tpTVpFVBYWtS+xOS7Q0mTUgGSP7RyGaau7F3FeTmSMUmJpRKfUOWrhC5BXklp4MGa8o7komq26d99fS0rXgvEq99wgQi5lgBHiQ9bvOqKATI3LB6YpchRwkRaH0RRg1DLjJA2PJ+Ycf9lYUfIha7KtYYzsVeQHG9DOKmjD/vJgWCaKc31aFdwZ5400wa5zdhLsljpyszTh6/BT7QvODOkWNFdGDR9YtojohU2DbZE4fTwCrCaoXVtEaInh8rPSB3fJaSKv5UPC6qYZMnjGB1w2/ifa5xJKewoxg4DNT5o3rVGjpjfbkAJ1YAK3iOkFhKIsGNxyKo6r1KFBzYpNetAGVxo8D0XwBYONYbs4xKj0w4Amg5fuQWXOX+c4M0td/nr4EP3GNwTQw4XqZ5M52mHocxe/3s4RUePB2WJtQjlTp3dY3RLkKXFtw2EUNI0PA3zA0wK3GDijQuuh9+ggOZoGvare3omUo6OQ6j5f4EmM5qyygFfvnwaQBdGl5Iw1cAFwcWqnNwead4swH2f5pi/zqIZweajKsXZiFX8K02kpOSaFo0IffuJ5dbgdYhvmpg4Fq5JwZbnz3QQ2HmL7sAWfoYCL7Ct9EIjLZGn3xnvLcMWqxfn1AqrOaQIP3sMtCt2zEHNW9cvTkQoFYAg/T2aEPy4S+AiU29w=
  app: simon-noteful-v4
  on:
    repo: thinkful-ei22/simon-noteful-v4
